### ISSUE TITLE
Adding New Learning Page

### ISSUE THREAD

**Issue by amankumarsahani** [Octet3290/OctetLearnings#1]
Your Learning Platform is great, and I would like to contribute to it. I have some ideas for adding new pages so if that is okay, I would like to also contribute to your project.

**Comment by Octet3290** [comment]
> Your Learning Platform is great, and I would like to contribute to it. I have some ideas for adding new pages so if that is okay, I would like to also contribute to your project.


Hey thanks for showing your interest in Octet's Learning. Please let me know your ideas on what contents you are going to add. I will assign you the issue accordingly.

**Comment by amankumarsahani** [comment]
I think I some content Regarding Machine Learning and cloud computing. So we can add some Content related to that. Sent from Mail for Windows From: RAHUL KUMAR YADAVSent: 05 October 2022 15:46To: Octet3290/OctetLearningsCc: Aman Kumar Sahani; AuthorSubject: Re: [Octet3290/OctetLearnings] Adding New Learning Page (Issue #1) Your Learning Platform is great, and I would like to contribute to it. I have some ideas for adding new pages so if that is okay, I would like to also contribute to your project.Hey thanks for showing your interest in Octet's Learning. Please let me know your ideas on what contents you are going to add. I will assign you the issue accordingly.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by amankumarsahani** [comment]
I think I some content Regarding Machine Learning and cloud computing. So we can add some Content related to that.

**Comment by Octet3290** [comment]
> I think I some content Regarding Machine Learning and cloud computing. So we can add some Content related to that.

Sounds good. Go ahead :)
