### ISSUE TITLE
Add new CSS learning Page in Web Development!

### ISSUE THREAD

**Issue by MashiBan** [Octet3290/OctetLearnings#2]
please assign this to me!

**Comment by Octet3290** [comment]
please let me know what you are going to add then I will assign you the issue accordingly.

**Comment by MashiBan** [comment]
We can add simple CSS syntax , tricks and  short cuts to syntax  and  unheard tags and features .

**Comment by Octet3290** [comment]
> We can add simple CSS syntax , tricks and  short cuts to syntax  and  unheard tags and features .

Go ahead :)
